### ISSUE TITLE
Project Flow

### ISSUE THREAD

**Issue by vidhithakkar12** [nagdevAmruthnath/Predictive-Maintenance#1]
Hello Nagdev,

Thank you for sharing your project. I would like to understand the project flow and description of the data that you have used. Looking forward to a quick response.

Thanks,
Vidhi

**Comment by nagdevAmruthnath** [comment]
@vidhithakkar12 Please see my notebooks for the project flow. 

1. Load the data
2. Summarize the data and extract features
3. Preprocess data
4. Understanding features
5. Set up experiments with different model, various sample sizes and hyper parameters
6. Build models for anomaly detection or fault classification
7. Test the models
8. Verify and validate the consistency of the results

The data used is vibration data with 3 axes (XYZ) with sample rate or 100Hz or 100 samples per second.
