### ISSUE TITLE
Flawed analysis including incorrect predictive modelling for Predictive Maintenance - Machine Learning.ipynb

### ISSUE THREAD

**Issue by ghost** [nagdevAmruthnath/Predictive-Maintenance#2]
The notebook, `Predictive Maintenance - Machine Learning.ipynb` predictive modelling is wrong.

This analysis is flawed because you are not using the original feature-set (read the original data variables). Rather, the summary statistics for the original feature-set like mean, median, sd are used as features and fed into some classification algorithms. I refer to cell 9 in this notebook

Off course, with the summary statistics as a feature-set any classifier/clustering will perform well!!

**Comment by nagdevAmruthnath** [comment]
The concept is called feature extraction in signal processing. When you are dealing with high frequency data between 1khz to 8 khz, you will be dealing with a lot of data (between 1000 samples to 8000 samples per second) and in most cases its impractical to use them as is. You need to extract features either statistical (mean, median, sd, kurtosis, skewness etc) or domain (in vibration peak velocity, acceleration RMS etc) or both to build strong models. 

The whole idea is to aggregate the samples by 1 second (1 second of data becomes 1 observation. This again depends on your sensor setting), build models on aggregated data and predict on aggregated data. 

Also, when we are dealing with sensor data, its recommended to convert them into frequency domain and use different filters (based on application). By  doing so, our 1000 time series samples becomes 2000+ samples. 

Hope this helps.
